//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncTPV.WSTPV {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSTPV.WSyncRomSoap")]
    public interface WSyncRomSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VersionWS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string VersionWS();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ping", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Ping();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidaUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void ValidaUsuario(string CLAVE, string NOMBRE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/validarDocumentosNoEnviadoDeUnAgente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void validarDocumentosNoEnviadoDeUnAgente(string claveAgente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void getData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAllDataAboutdistributor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void getAllDataAboutdistributor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExisteRuta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ExisteRuta(string RUTA, int USUARIO_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DTArticulos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DTArticulos(string ruta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DTBANCOS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DTBANCOS();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DTBENEFICIARIO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DTBENEFICIARIO();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DTCATVISITAS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DTCATVISITAS();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DTCATRECHAZOS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DTCATRECHAZOS();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DTCIUDADES", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DTCIUDADES(string ruta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DTESTADOS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DTESTADOS(string ruta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DTHISTORIALVENTA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DTHISTORIALVENTA(string RUTA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DTCLIENTES", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DTCLIENTES(string ruta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DTFORMASCOBRO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DTFORMASCOBRO();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DTFORMASPAGOVENTAS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DTFORMASPAGOVENTAS();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DTGRUPOS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DTGRUPOS(string RUTA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DTLINEAS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DTLINEAS(string RUTA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DTPRECIOSARTICULOS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DTPRECIOSARTICULOS();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DTPRECIOSEMPRESA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DTPRECIOSEMPRESA();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DTUSUARIOS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DTUSUARIOS();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DTZONASCLIENTES", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DTZONASCLIENTES(string RUTA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DTCREDITOS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DTCREDITOS(string RUTA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DatosTicket", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DatosTicket();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DTPAGOSCREDITO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DTPAGOSCREDITO(string RUTA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertar_cliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string insertar_cliente(string NOMBREU, string nombre, int zonacliente, int ciudad_id, int estado_id, string calle, string numero, string colonia, string poblacion, string referencia, string telefono, string cp, string email, string rfc, string notas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/APLICA_DOCTO_VENTA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string APLICA_DOCTO_VENTA(string DOCTO_ID_PEDIDO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LIBERA_DOCTOINV", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string LIBERA_DOCTOINV(int DOCTO_ID_PEDIDO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRECHAZAPEDIDO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string FRECHAZAPEDIDO(int PEDIDO_ID, int USUARIO_ID, int RAZON_ID, string FECHAHORA, string LATITUD, string LONGITUD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FACTUALIZAGPS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string FACTUALIZAGPS(int USUARIO_ID, string FECHAHORA, string LATITUD, string LONGITUD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insertar_PedidosEncabezado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Insertar_PedidosEncabezado(
                    string clave_cliente, 
                    int cliente_id, 
                    decimal descuento, 
                    decimal total, 
                    string NOMBREU, 
                    int ALMACEN_ID, 
                    decimal ANTICIPO, 
                    string TIPO_DOCUMENTO, 
                    int FORMA_COBRO_ID, 
                    int FACTURA, 
                    string observacion, 
                    int DEV, 
                    string FVENTA, 
                    string FECHAHORAMOV, 
                    int USUARIO_ID, 
                    int FORMA_COBRO_ID_ABONO, 
                    int CIDDOCTOPEDIDOCC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insertar_encabezado_documento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Insertar_encabezado_documento(SyncTPV.WSTPV.clsEncabezado encabezado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insertar_PedidosDetalle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Insertar_PedidosDetalle(int DOCTO_ID_PEDIDO, string CLAVE_ART, int ARTICULO_ID, decimal unidades, decimal precio, decimal TOTAL, int POSICION, string TIPO_DOCUMENTO, string NOMBREU, string FACTURA, decimal DESCUENTO, string OBSERVACIONES, int IDDEV, string COMENTARIO, int USUARIO_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertar_cuentasxcobrar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string insertar_cuentasxcobrar(string NATURALEZA, string FOLIO, string CLAVE_CLI, int CLIENTE_ID, decimal IMPORTE, int DOCTO_APLICAR, string NOMBREU, int FORMA_COBRO_CC_ID, string REFER_MOVTO_BANCARIO, string FECHA, string FECHAHORAMOV, string FOLIODOCTO, int ESTATUS, int USUARIO_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertar_gps", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string insertar_gps(string LAT, string LON, int CLIENTE_ID, string FECHA, int TIPO_MOV, int VENDEDOR_ID, string RUTA, int idDocto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DTCLIENTEPEDIDO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DTCLIENTEPEDIDO(string ruta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FCARGAPEDIDOENCABEZADO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void FCARGAPEDIDOENCABEZADO(int USUARIO_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FCARGAPEDIDODETALLE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void FCARGAPEDIDODETALLE(int DOCTO_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerfcm", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void obtenerfcm(int USUARIO_ID, string fcm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DTPLAN_VISITAS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DTPLAN_VISITAS(string RUTA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DTDESCUENTOS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DTDESCUENTOS();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DTCAJAPAQUETES", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DTCAJAPAQUETES();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DTCATALOGO_PROMOCIONES_VIGENTES", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DTCATALOGO_PROMOCIONES_VIGENTES();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DTDETALLE_PROMOCIONES_ARTICULOS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DTDETALLE_PROMOCIONES_ARTICULOS();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DTDETALLE_DESC_VOLUMENLINEAS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DTDETALLE_DESC_VOLUMENLINEAS();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DTDETALLE_PROMOCIONES_ARTICULOS_CLIENTES", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DTDETALLE_PROMOCIONES_ARTICULOS_CLIENTES();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DTDETALLE_PROMOCIONES_GRUPO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DTDETALLE_PROMOCIONES_GRUPO();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DTDETALLE_PROMOCIONES_LINEA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DTDETALLE_PROMOCIONES_LINEA();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ABRIRCAJA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ABRIRCAJA(decimal MONTO, string NOMBREU, int VENDEDOR_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CERRARCAJA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CERRARCAJA(decimal MONTO, string NOMBREU, int VENDEDOR_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INSERT_BITACORA_LECTURA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string INSERT_BITACORA_LECTURA(int CLIENTE_ID, string FECHA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INSERT_HISTORIALCXC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string INSERT_HISTORIALCXC(string FOLIO, string USUARIO, string MONTO, string FECHAHORAMOV, string FORMAPAGO, string FOLIONUEVO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VALIDACAJA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string VALIDACAJA(string NOMBREU, int VENDEDOR_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VALIDA_MAC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string VALIDA_MAC(string MAC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualiza_plan_visitas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string actualiza_plan_visitas(int visita_id, int RAZON_VIS_INEF_ID, string observaciones);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insertar_PedidosEncabezado2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Insertar_PedidosEncabezado2();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsEncabezado : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cIDCLIENTEPROVEEDORField;
        
        private string cCODIGOCLIENTEField;
        
        private int cIDAGENTEField;
        
        private string cNOMBREAGENTEField;
        
        private double cDESCUENTODOC1Field;
        
        private double cTOTALField;
        
        private int idAlmacenField;
        
        private double aNTICIPOField;
        
        private int cIDDOCUMENTODEField;
        
        private int cMETODOPAGField;
        
        private int fACTURAField;
        
        private string cOBSERVACIONESField;
        
        private int dEVField;
        
        private string cFECHAField;
        
        private string cRUTAField;
        
        private string cREFERENCIAField;
        
        private int iDPEDIDOCALLCField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int CIDCLIENTEPROVEEDOR {
            get {
                return this.cIDCLIENTEPROVEEDORField;
            }
            set {
                this.cIDCLIENTEPROVEEDORField = value;
                this.RaisePropertyChanged("CIDCLIENTEPROVEEDOR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CCODIGOCLIENTE {
            get {
                return this.cCODIGOCLIENTEField;
            }
            set {
                this.cCODIGOCLIENTEField = value;
                this.RaisePropertyChanged("CCODIGOCLIENTE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int CIDAGENTE {
            get {
                return this.cIDAGENTEField;
            }
            set {
                this.cIDAGENTEField = value;
                this.RaisePropertyChanged("CIDAGENTE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CNOMBREAGENTE {
            get {
                return this.cNOMBREAGENTEField;
            }
            set {
                this.cNOMBREAGENTEField = value;
                this.RaisePropertyChanged("CNOMBREAGENTE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public double CDESCUENTODOC1 {
            get {
                return this.cDESCUENTODOC1Field;
            }
            set {
                this.cDESCUENTODOC1Field = value;
                this.RaisePropertyChanged("CDESCUENTODOC1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public double CTOTAL {
            get {
                return this.cTOTALField;
            }
            set {
                this.cTOTALField = value;
                this.RaisePropertyChanged("CTOTAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int idAlmacen {
            get {
                return this.idAlmacenField;
            }
            set {
                this.idAlmacenField = value;
                this.RaisePropertyChanged("idAlmacen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public double ANTICIPO {
            get {
                return this.aNTICIPOField;
            }
            set {
                this.aNTICIPOField = value;
                this.RaisePropertyChanged("ANTICIPO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int CIDDOCUMENTODE {
            get {
                return this.cIDDOCUMENTODEField;
            }
            set {
                this.cIDDOCUMENTODEField = value;
                this.RaisePropertyChanged("CIDDOCUMENTODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int CMETODOPAG {
            get {
                return this.cMETODOPAGField;
            }
            set {
                this.cMETODOPAGField = value;
                this.RaisePropertyChanged("CMETODOPAG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int FACTURA {
            get {
                return this.fACTURAField;
            }
            set {
                this.fACTURAField = value;
                this.RaisePropertyChanged("FACTURA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string COBSERVACIONES {
            get {
                return this.cOBSERVACIONESField;
            }
            set {
                this.cOBSERVACIONESField = value;
                this.RaisePropertyChanged("COBSERVACIONES");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int DEV {
            get {
                return this.dEVField;
            }
            set {
                this.dEVField = value;
                this.RaisePropertyChanged("DEV");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string CFECHA {
            get {
                return this.cFECHAField;
            }
            set {
                this.cFECHAField = value;
                this.RaisePropertyChanged("CFECHA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string CRUTA {
            get {
                return this.cRUTAField;
            }
            set {
                this.cRUTAField = value;
                this.RaisePropertyChanged("CRUTA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string CREFERENCIA {
            get {
                return this.cREFERENCIAField;
            }
            set {
                this.cREFERENCIAField = value;
                this.RaisePropertyChanged("CREFERENCIA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public int IDPEDIDOCALLC {
            get {
                return this.iDPEDIDOCALLCField;
            }
            set {
                this.iDPEDIDOCALLCField = value;
                this.RaisePropertyChanged("IDPEDIDOCALLC");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSyncRomSoapChannel : SyncTPV.WSTPV.WSyncRomSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSyncRomSoapClient : System.ServiceModel.ClientBase<SyncTPV.WSTPV.WSyncRomSoap>, SyncTPV.WSTPV.WSyncRomSoap {
        
        public WSyncRomSoapClient() {
        }
        
        public WSyncRomSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSyncRomSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSyncRomSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSyncRomSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string VersionWS() {
            return base.Channel.VersionWS();
        }
        
        public string Ping() {
            return base.Channel.Ping();
        }
        
        public void ValidaUsuario(string CLAVE, string NOMBRE) {
            base.Channel.ValidaUsuario(CLAVE, NOMBRE);
        }
        
        public void validarDocumentosNoEnviadoDeUnAgente(string claveAgente) {
            base.Channel.validarDocumentosNoEnviadoDeUnAgente(claveAgente);
        }
        
        public void getData() {
            base.Channel.getData();
        }
        
        public void getAllDataAboutdistributor() {
            base.Channel.getAllDataAboutdistributor();
        }
        
        public string ExisteRuta(string RUTA, int USUARIO_ID) {
            return base.Channel.ExisteRuta(RUTA, USUARIO_ID);
        }
        
        public void DTArticulos(string ruta) {
            base.Channel.DTArticulos(ruta);
        }
        
        public void DTBANCOS() {
            base.Channel.DTBANCOS();
        }
        
        public void DTBENEFICIARIO() {
            base.Channel.DTBENEFICIARIO();
        }
        
        public void DTCATVISITAS() {
            base.Channel.DTCATVISITAS();
        }
        
        public void DTCATRECHAZOS() {
            base.Channel.DTCATRECHAZOS();
        }
        
        public void DTCIUDADES(string ruta) {
            base.Channel.DTCIUDADES(ruta);
        }
        
        public void DTESTADOS(string ruta) {
            base.Channel.DTESTADOS(ruta);
        }
        
        public void DTHISTORIALVENTA(string RUTA) {
            base.Channel.DTHISTORIALVENTA(RUTA);
        }
        
        public void DTCLIENTES(string ruta) {
            base.Channel.DTCLIENTES(ruta);
        }
        
        public void DTFORMASCOBRO() {
            base.Channel.DTFORMASCOBRO();
        }
        
        public void DTFORMASPAGOVENTAS() {
            base.Channel.DTFORMASPAGOVENTAS();
        }
        
        public void DTGRUPOS(string RUTA) {
            base.Channel.DTGRUPOS(RUTA);
        }
        
        public void DTLINEAS(string RUTA) {
            base.Channel.DTLINEAS(RUTA);
        }
        
        public void DTPRECIOSARTICULOS() {
            base.Channel.DTPRECIOSARTICULOS();
        }
        
        public void DTPRECIOSEMPRESA() {
            base.Channel.DTPRECIOSEMPRESA();
        }
        
        public void DTUSUARIOS() {
            base.Channel.DTUSUARIOS();
        }
        
        public void DTZONASCLIENTES(string RUTA) {
            base.Channel.DTZONASCLIENTES(RUTA);
        }
        
        public void DTCREDITOS(string RUTA) {
            base.Channel.DTCREDITOS(RUTA);
        }
        
        public void DatosTicket() {
            base.Channel.DatosTicket();
        }
        
        public void DTPAGOSCREDITO(string RUTA) {
            base.Channel.DTPAGOSCREDITO(RUTA);
        }
        
        public string insertar_cliente(string NOMBREU, string nombre, int zonacliente, int ciudad_id, int estado_id, string calle, string numero, string colonia, string poblacion, string referencia, string telefono, string cp, string email, string rfc, string notas) {
            return base.Channel.insertar_cliente(NOMBREU, nombre, zonacliente, ciudad_id, estado_id, calle, numero, colonia, poblacion, referencia, telefono, cp, email, rfc, notas);
        }
        
        public string APLICA_DOCTO_VENTA(string DOCTO_ID_PEDIDO) {
            return base.Channel.APLICA_DOCTO_VENTA(DOCTO_ID_PEDIDO);
        }
        
        public string LIBERA_DOCTOINV(int DOCTO_ID_PEDIDO) {
            return base.Channel.LIBERA_DOCTOINV(DOCTO_ID_PEDIDO);
        }
        
        public string FRECHAZAPEDIDO(int PEDIDO_ID, int USUARIO_ID, int RAZON_ID, string FECHAHORA, string LATITUD, string LONGITUD) {
            return base.Channel.FRECHAZAPEDIDO(PEDIDO_ID, USUARIO_ID, RAZON_ID, FECHAHORA, LATITUD, LONGITUD);
        }
        
        public string FACTUALIZAGPS(int USUARIO_ID, string FECHAHORA, string LATITUD, string LONGITUD) {
            return base.Channel.FACTUALIZAGPS(USUARIO_ID, FECHAHORA, LATITUD, LONGITUD);
        }
        
        public string Insertar_PedidosEncabezado(
                    string clave_cliente, 
                    int cliente_id, 
                    decimal descuento, 
                    decimal total, 
                    string NOMBREU, 
                    int ALMACEN_ID, 
                    decimal ANTICIPO, 
                    string TIPO_DOCUMENTO, 
                    int FORMA_COBRO_ID, 
                    int FACTURA, 
                    string observacion, 
                    int DEV, 
                    string FVENTA, 
                    string FECHAHORAMOV, 
                    int USUARIO_ID, 
                    int FORMA_COBRO_ID_ABONO, 
                    int CIDDOCTOPEDIDOCC) {
            return base.Channel.Insertar_PedidosEncabezado(clave_cliente, cliente_id, descuento, total, NOMBREU, ALMACEN_ID, ANTICIPO, TIPO_DOCUMENTO, FORMA_COBRO_ID, FACTURA, observacion, DEV, FVENTA, FECHAHORAMOV, USUARIO_ID, FORMA_COBRO_ID_ABONO, CIDDOCTOPEDIDOCC);
        }
        
        public string Insertar_encabezado_documento(SyncTPV.WSTPV.clsEncabezado encabezado) {
            return base.Channel.Insertar_encabezado_documento(encabezado);
        }
        
        public string Insertar_PedidosDetalle(int DOCTO_ID_PEDIDO, string CLAVE_ART, int ARTICULO_ID, decimal unidades, decimal precio, decimal TOTAL, int POSICION, string TIPO_DOCUMENTO, string NOMBREU, string FACTURA, decimal DESCUENTO, string OBSERVACIONES, int IDDEV, string COMENTARIO, int USUARIO_ID) {
            return base.Channel.Insertar_PedidosDetalle(DOCTO_ID_PEDIDO, CLAVE_ART, ARTICULO_ID, unidades, precio, TOTAL, POSICION, TIPO_DOCUMENTO, NOMBREU, FACTURA, DESCUENTO, OBSERVACIONES, IDDEV, COMENTARIO, USUARIO_ID);
        }
        
        public string insertar_cuentasxcobrar(string NATURALEZA, string FOLIO, string CLAVE_CLI, int CLIENTE_ID, decimal IMPORTE, int DOCTO_APLICAR, string NOMBREU, int FORMA_COBRO_CC_ID, string REFER_MOVTO_BANCARIO, string FECHA, string FECHAHORAMOV, string FOLIODOCTO, int ESTATUS, int USUARIO_ID) {
            return base.Channel.insertar_cuentasxcobrar(NATURALEZA, FOLIO, CLAVE_CLI, CLIENTE_ID, IMPORTE, DOCTO_APLICAR, NOMBREU, FORMA_COBRO_CC_ID, REFER_MOVTO_BANCARIO, FECHA, FECHAHORAMOV, FOLIODOCTO, ESTATUS, USUARIO_ID);
        }
        
        public string insertar_gps(string LAT, string LON, int CLIENTE_ID, string FECHA, int TIPO_MOV, int VENDEDOR_ID, string RUTA, int idDocto) {
            return base.Channel.insertar_gps(LAT, LON, CLIENTE_ID, FECHA, TIPO_MOV, VENDEDOR_ID, RUTA, idDocto);
        }
        
        public void DTCLIENTEPEDIDO(string ruta) {
            base.Channel.DTCLIENTEPEDIDO(ruta);
        }
        
        public void FCARGAPEDIDOENCABEZADO(int USUARIO_ID) {
            base.Channel.FCARGAPEDIDOENCABEZADO(USUARIO_ID);
        }
        
        public void FCARGAPEDIDODETALLE(int DOCTO_ID) {
            base.Channel.FCARGAPEDIDODETALLE(DOCTO_ID);
        }
        
        public void obtenerfcm(int USUARIO_ID, string fcm) {
            base.Channel.obtenerfcm(USUARIO_ID, fcm);
        }
        
        public void DTPLAN_VISITAS(string RUTA) {
            base.Channel.DTPLAN_VISITAS(RUTA);
        }
        
        public void DTDESCUENTOS() {
            base.Channel.DTDESCUENTOS();
        }
        
        public void DTCAJAPAQUETES() {
            base.Channel.DTCAJAPAQUETES();
        }
        
        public void DTCATALOGO_PROMOCIONES_VIGENTES() {
            base.Channel.DTCATALOGO_PROMOCIONES_VIGENTES();
        }
        
        public void DTDETALLE_PROMOCIONES_ARTICULOS() {
            base.Channel.DTDETALLE_PROMOCIONES_ARTICULOS();
        }
        
        public void DTDETALLE_DESC_VOLUMENLINEAS() {
            base.Channel.DTDETALLE_DESC_VOLUMENLINEAS();
        }
        
        public void DTDETALLE_PROMOCIONES_ARTICULOS_CLIENTES() {
            base.Channel.DTDETALLE_PROMOCIONES_ARTICULOS_CLIENTES();
        }
        
        public void DTDETALLE_PROMOCIONES_GRUPO() {
            base.Channel.DTDETALLE_PROMOCIONES_GRUPO();
        }
        
        public void DTDETALLE_PROMOCIONES_LINEA() {
            base.Channel.DTDETALLE_PROMOCIONES_LINEA();
        }
        
        public string ABRIRCAJA(decimal MONTO, string NOMBREU, int VENDEDOR_ID) {
            return base.Channel.ABRIRCAJA(MONTO, NOMBREU, VENDEDOR_ID);
        }
        
        public string CERRARCAJA(decimal MONTO, string NOMBREU, int VENDEDOR_ID) {
            return base.Channel.CERRARCAJA(MONTO, NOMBREU, VENDEDOR_ID);
        }
        
        public string INSERT_BITACORA_LECTURA(int CLIENTE_ID, string FECHA) {
            return base.Channel.INSERT_BITACORA_LECTURA(CLIENTE_ID, FECHA);
        }
        
        public string INSERT_HISTORIALCXC(string FOLIO, string USUARIO, string MONTO, string FECHAHORAMOV, string FORMAPAGO, string FOLIONUEVO) {
            return base.Channel.INSERT_HISTORIALCXC(FOLIO, USUARIO, MONTO, FECHAHORAMOV, FORMAPAGO, FOLIONUEVO);
        }
        
        public string VALIDACAJA(string NOMBREU, int VENDEDOR_ID) {
            return base.Channel.VALIDACAJA(NOMBREU, VENDEDOR_ID);
        }
        
        public string VALIDA_MAC(string MAC) {
            return base.Channel.VALIDA_MAC(MAC);
        }
        
        public string actualiza_plan_visitas(int visita_id, int RAZON_VIS_INEF_ID, string observaciones) {
            return base.Channel.actualiza_plan_visitas(visita_id, RAZON_VIS_INEF_ID, observaciones);
        }
        
        public string Insertar_PedidosEncabezado2() {
            return base.Channel.Insertar_PedidosEncabezado2();
        }
    }
}
